class UserAlreadyExistsError(Exception):
    """
    This is an exception to catch if a user exists already
    """
    pass